- id: 1
  title: My Portfolio
  description: A personal portfolio showcasing my work, skills, and experience as
    a software engineer.
  status: 1
  readme_url: https://github.com/MayuKuno/ninefs_portfolio
  website_url: https://ninefs-portfolio.onrender.com/
  features: '・Like Feature

    ・Tags

    ・Responsive UI

    ・Pride Mode'
  tech_stacks:
  - name: Ruby on Rails
    category: Backend
  - name: PostgreSQL
    category: Database
  - name: Ruby
    category: Backend
  - name: Render
    category: Infrastructure
  - name: Javascript
    category: DevOps
  images:
  - image: portfolio.png
    is_main: true
  - image: portfolio_2.gif
    is_main: false
- id: 2
  title: Pride Frame
  description: An empowering web app where users can upload photos, add vibrant pride-themed
    frames, and share their creations on social media.
  status: 1
  readme_url: https://github.com/MayuKuno/pride-frame
  website_url: https://dl1mzzuw9wm0m.cloudfront.net/
  features: |-
    ・Create Pride Profile Pictures  
    ・Upload Custom Pride Frames  
    ・Browse and Share in the Gallery
  tech_stacks:
    - name: Vue 3
      category: Frontend
    - name: TypeScript
      category: Frontend
    - name: Vuetify
      category: Frontend
    - name: AWS Lambda
      category: Backend
    - name: AWS API Gateway
      category: Backend
    - name: Amazon S3
      category: Storage
    - name: DynamoDB
      category: Database
    - name: CloudFront
      category: Hosting
    - name: Serverless Framework
      category: Deployment
    - name: GitHub Actions
      category: DevOps
  images:
    - image: prideframe.png
      is_main: true
    - image: prideframe_2.png
      is_main: false
